// <auto-generated />
using System;
using EmissionDataRecordService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmissionDataRecordService.Migrations
{
    [DbContext(typeof(EmissionDbContext))]
    [Migration("20250609110447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmissionDataRecordService.Model.EmissionDataRecord", b =>
                {
                    b.Property<string>("Material_Number")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Iso_Country_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Cartridges_Rounded_KgCO2")
                        .HasColumnType("float");

                    b.Property<int>("Category_ID")
                        .HasColumnType("int");

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Consumables_Rounded_KgCO2")
                        .HasColumnType("float");

                    b.Property<double>("Energy_Use_Rounded_KgCO2")
                        .HasColumnType("float");

                    b.Property<double>("Eol_Rounded_KgCO2")
                        .HasColumnType("float");

                    b.Property<DateTime>("Insert_Gmt_Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Logical_Deletion_Indicator")
                        .HasColumnType("bit");

                    b.Property<string>("Material_Hierarchy_Model_Node_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material_Hierarchy_Parent_Hierarchy_Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Paper_Rounded_KgCO2")
                        .HasColumnType("float");

                    b.Property<double>("Production_Rounded_KgCO2")
                        .HasColumnType("float");

                    b.Property<DateTime>("Source_Create_Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Source_System_Update_Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("Total_Lower_Bounds_KgCO2")
                        .HasColumnType("float");

                    b.Property<double>("Total_Rounded_KgCO2")
                        .HasColumnType("float");

                    b.Property<double>("Total_Upper_Bounds_KgCO2")
                        .HasColumnType("float");

                    b.Property<double>("Transport_Rounded_KgCO2")
                        .HasColumnType("float");

                    b.HasKey("Material_Number", "Iso_Country_Code");

                    b.ToTable("EmissionDataRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
